language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rspec
before_script:
  - mysql -e 'create database roadtrip_test'
  - RAILS_ENV=test bundle exec rake --trace db:migrate:reset
