common: &common
  adapter: mysql2
  pool_size: 1
  wait_timeout: 10     # max time to wait for a connection from the pool, in ms
  connect_timeout: 50  # max time to wait for a db connection, in ms
  read_timeout: 1000   # read timeouts in ms
  write_timeout: 1000  # write timeouts in ms
  reconnect: true

local: &local
  <<: *common
  host: localhost
  password:
  username: root

development:
  <<: *local
  database: roadtrip_development

test:
  <<: *local
  database: roadtrip_test

production:
  <<: *local
  database: roadtrip_production
